### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by StephanTLavavej**
This is structured as a series of commits for easier reviewing.

* Remove unused declarations: `JE_loadOrderingInfo()`, `JE_buttonPressed()`.
  + And remove the "shareware version check", which has no side effects.
* Remove unused function `JE_drawFrame()`.
* Remove unused `sizebuf` functions: `SZ_Memcpy()`, `SZ_GetCurBufferPtr()`, `MSG_WriteByte()`, `MSG_WriteWord()`, `MSG_WriteDWord()`, `MSG_ReadDWord()`.
  + And update a comment now that `SZ_Memcpy()` is gone, leaving only `SZ_Memcpy2()`.
* Remove unused `config_file` functions: `config_find_sections()`, `config_get_or_set_string_option()`, `config_get_or_set_uint_option()`.
* Remove unused `fwrite` functions: `fwrite_s16_die()`, `fwrite_u32_die()`, `fwrite_s32_die()`.
* Remove no-op functions `JE_clearKeyboard()`, `JE_wipeKey()`, `JE_wackyCol()`.
* Remove unused macros: `foreach_option_value`, `UNIT_HEIGHT`, `NO_SHADE`, `ARMOR_NUM`, `ENGINE_NUM`, `LVL_NUM`, `LVL_NUM_2`, `LVL_NUM_3`, `LVL_NUM_4`, `LVL_NUM_5`.
  + The `LVL_NUM` family became unused after 0af1efb81d7d09235ca8d384eee0d8550efc1ff4.
* Remove unused variables `frameCount2`, `sound_init_state`.
* Remove dead variables `frameCount`, `notYetLoadedSound`, `quitRequested`.
  + These are written to, but never read.
* Remove never-assigned variable `waitToEndLevel`.
  + Static initialization means it's always `false`.
* Remove never-assigned variable `mouse_has_three_buttons`.
  + It's always `true`.
* Remove unused `ConfigBoolStyle`/`bool_values` entries.
  + `ZERO_ONE` and `FALSE_TRUE` were never used by the code. These enumerators aren't persisted anywhere, so there's no file compatibility concern, but we do need to re-number the remaining enumerators starting from `0`. Add a comment explaining why.
* Remove unused fields from `JE_SingleEnemyType`.
  + `fillbyte` and `fill1` were completely unused.
  + `exca`, `eyca`, and `enemydatofs` were dead.
  + As far as I can tell, the layout of this struct poses no compatibility concerns (I don't see it being directly read from files, and `JE_makeEnemy()` assigns each field).
  + On x64, this decreases the struct size from 152 to 144 bytes.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Oh, interesting! The Linux build failed with:

```
src/tyrian2.c: In function ‘JE_drawEnemy’:
src/tyrian2.c:389:8: error: a label can only be part of a statement and a declaration is not a statement
  389 |        const int attractivity = 4 - (abs(player[0].x - tempX) + abs(player[0].y - tempY)) / 100;
      |        ^~~~~
```

This explains what those semicolons were doing. (MSVC apparently doesn't complain about this.) I'd like to replace that technique with C++-friendly braces instead, but that's not a pure removal, so I'll drop this commit from the PR.

**Comment by StephanTLavavej** [comment]
Rebased to resolve conflicts. Also dropped the removal of the `right_aligned` enumerator as it's now used.

**Comment by carlreinke** [comment]
I picked a few of these removals that seemed obviously good to me.  The remaining removals fall into a few buckets -- (1) code that is unused but requires some investigation into whether that was the result of a mistake when porting the code, (2) code that is unused but is helpful when comparing the ported code to the original code, and (3) code that is unused but would be useful if someone were to reuse the code in another project.

**Comment by StephanTLavavej** [comment]
Thank you! :tada: Feel free to close this PR, or let me know if you'd like me to rebase it so the bucket-1 removals can be investigated at some later time.

**Pull request closed without merging**
