### PR TITLE
Fix audio conversion

### LINKED ISSUE #30: Mangled audio when system wants 48 kHz, 32-bit, 2-channel
Tyrian's audio is completely mangled on my machine - it's not quite pure noise, but nearly so.

I noticed that my machine was giving SDL 48 kHz audio. By patching `loudness.c`, I found another difference. I changed:

https://github.com/opentyrian/opentyrian/blob/d4f5aff9144de4bb23ebc1c391e7fcf8085a27f1/src/loudness.c#L69
to:
```c
	printf("\trequested %d Hz, %d bits, %d channels, %d samples\n", ask.freq, (int)SDL_AUDIO_BITSIZE(ask.format), ask.channels, ask.samples);
```
and:
https://github.com/opentyrian/opentyrian/blob/d4f5aff9144de4bb23ebc1c391e7fcf8085a27f1/src/loudness.c#L78
to:
```c
	printf("\tobtained  %d Hz, %d bits, %d channels, %d samples\n", got.freq, (int)SDL_AUDIO_BITSIZE(got.format), got.channels, got.samples);
```

(I would be happy to contribute this as a PR if desired, as it seems to be useful info.)

With this, my machine prints:

```
requested 44100 Hz, 16 bits, 1 channels, 2048 samples
obtained  48000 Hz, 32 bits, 2 channels, 480 samples
```

I don't completely understand the audio callback here, but it looks like it's not prepared to handle this kind of conversion, especially because it appears to require a large amount of temporary buffer space (SDL's documentation warns that the necessary temporary buffer may be larger than either the input or the output size, but this callback assumes it can always work within the output space):
https://github.com/opentyrian/opentyrian/blob/d4f5aff9144de4bb23ebc1c391e7fcf8085a27f1/src/loudness.c#L89-L181

Some investigation:

1. If I hack
   https://github.com/opentyrian/opentyrian/blob/d4f5aff9144de4bb23ebc1c391e7fcf8085a27f1/src/loudness.c#L63
   to say:
   ```c
   ask.freq = 48000;
   ```
   then I get smooth but fast audio. (I think/expect it's higher pitch too, but I'm bad with tones, so can't tell.) This indicates that the problem is indeed in the conversion, not elsewhere in the audio code, although it's useless for a fix.

2. I can't seem to get my system to provide 44.1 kHz audio regardless of how I adjust what's asked for - it really wants to provide 48 kHz. I'm running Windows 11. (Possibly worth noting that I'm using SDL 2.0.16 via vcpkg.)

3. In `audio_cb()`, `howmuch` is `3840` and `audio_cvt.len_mult` is `16` for me.

4. I tried fixing `audio_cb()` to use a larger temporary buffer (it appears that `SDL_ConvertAudio()` will convert the frequency, bitness, and channels). I got something that was listenable, and seemed to have the right speed, but had rapid crackling, so I'm clearly doing something wrong. I can provide that branch of horrible hacking if it would be of interest.

Please let me know if I can provide audio captures or any other info that would help! :smile_cat:

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #30, an issue affecting systems where the output format is 48 kHz, which requires a nontrivial conversion. There were two overlapping problems:

* As the [`SDL_AudioCVT` documentation](https://wiki.libsdl.org/SDL_AudioCVT) explains, "The audio buffer may need to be larger than either the original data or the converted data." `audio_cb()` didn't handle this case.
* `SDL_AudioCVT` is inherently unusable here, because OpenTyrian generates sound data in chunks. https://wiki.libsdl.org/Tutorials-AudioStream explains the root cause:

> From the dawn of time, until SDL 2.0.6, there was only one way to convert audio through SDL: By using the `SDL_AudioCVT` structure.
>
> It's a usable API, for various needs, but it has a few problems:
>
> * [...]
> * Perhaps most importantly: it can't resample data in chunks. You have to give it all the data it expects in one shot, or you'll get gaps and skips in your audio output.

This PR originally used `SDL_AudioStream` to manually convert audio properly, but @carlreinke found a better method. https://wiki.libsdl.org/SDL_OpenAudioDevice says:

> If your application can only handle one specific data format, pass a zero for `allowed_changes` and let SDL transparently handle any differences.

So here's what this PR is doing:

* Fix audio conversion by calling `SDL_OpenAudioDevice()` with `0` `allowed_changes`.
* Also add `SAMPLE_RATE` and use it everywhere.
  + In `loudness.c`, the global variable `freq` was never modified, so we can use the new constant directly.
  + Note that `opl.h` uses `SAMPLE_RATE` "before" `loudness.h` defines it, but this was already happening with `OUTPUT_QUALITY`, so every expansion of `opl_init()` must already be including `loudness.h`.
* Also rephrase the sample buffer size request from `2048` to `512 * OUTPUT_QUALITY`. This has no effect for the default `OUTPUT_QUALITY` of `4`, but it fixes unintentional latency when the `OUTPUT_QUALITY` is reduced to `2`.
* For clarity, rename `audio_cb()`'s `howmuch` to `bytes_needed`, and add `samples_needed`. Then update `audio_cb()`'s declaration to match.
* Add top-level `const` to `feedme`.

### CODE REVIEW

**Review by carlreinke — CHANGES_REQUESTED** [review]

**Comment by carlreinke** [comment]
> (As far as I can tell, the only alternative would be to convert all music and sound upon loading, which seems especially difficult for the music given how it's generated.)

Actually, I think doing conversion up front may be the right solution in the end.  Only the sound effects would need to be resampled, as the OPL emulator seems to support arbitrary sample rates (though it using a hard-coded sample rate right now).  Then that just leaves format conversion, which `AudioCVT` ought to be able to handle (since it shouldn't need any buffering).

**Comment by StephanTLavavej** [comment]
Thanks, I've pushed changes as requested. (As separate commits, for ease of incremental reviewing, but this PR can definitely be squashed when merging.)

* Omit spaces after casts.
* Add `SAMPLE_RATE` and use it everywhere.
  + In `loudness.c`, the global variable `freq` was never modified, so we can use the new constant directly.
  + Note that `opl.h` uses `SAMPLE_RATE` "before" `loudness.h` defines it, but this was already happening with `OUTPUT_QUALITY`, so every expansion of `opl_init()` must already be including `loudness.h`.

> Actually, I think doing conversion up front may be the right solution in the end. Only the sound effects would need to be resampled, as the OPL emulator seems to support arbitrary sample rates (though it is using a hard-coded sample rate right now). Then that just leaves format conversion, which AudioCVT ought to be able to handle (since it shouldn't need any buffering).

Oh cool! I think `SDL_AudioStream` might be easier to use for an up-front conversion too, since it avoids the need to calculate and allocate an intermediate buffer. `SDL_AudioStreamFlush()` will tell it that we're converting a complete sound effect.

**Comment by carlreinke** [comment]
Having looked at the SDL 2 docs a bit more, it looks like we could use [`SDL_OpenAudioDevice()`](https://wiki.libsdl.org/SDL_OpenAudioDevice) with `allowed_changes = 0` (rather than `SDL_OpenAudio()`).  That would simplify the code a bit and also get rid of the extra buffering.

We would also be able to get rid of the "requested" and "obtained" messages since we should always get what we asked for (or an error if SDL wouldn't be able to do the conversion in any case).

**Comment by StephanTLavavej** [comment]
Unfortunately, that simply fails on my machine. I tried:

```diff
-       if (SDL_OpenAudio(&ask, &got) == -1)
+       if (SDL_OpenAudioDevice(/*device*/ NULL, /*iscapture*/ 0, /*desired*/ &ask, /*obtained*/ &got, /*allowed_changes*/ 0) == 0)
```

and got:

```
initializing SDL audio...
        requested 44100 Hz, 16 bits, 1 channels, 2048 samples
error: failed to initialize SDL audio: Audio subsystem is not initialized
```

It appears that `allowed_changes = 0` doesn't force SDL to perform conversions behind the scenes, if the audio device insists on being given a particular format.

**Comment by carlreinke** [comment]
Looks like `SDL_OpenAudioDevice()` doesn't automatically initialize the audio subsytem.  Try adding
```
SDL_InitSubSystem(SDL_INIT_AUDIO);
```

**Comment by StephanTLavavej** [comment]
Aha, thanks! I tried this experimental commit (on top of this `SDL_AudioStream` PR, since I know that it plays sound correctly regardless of input/output formats):

https://github.com/StephanTLavavej/opentyrian/commit/f4f3a2d55a16b2195b8e04c6360dbd7ac0875ccd

```
initializing SDL audio...
        requested 44100 Hz, 16 bits, 1 channels, 2048 samples
        obtained  44100 Hz, 16 bits, 1 channels, 2048 samples
```

Now initialization succeeds, but I simply don't hear anything. Same thing happens (without the "16 bits" info that I added) if I apply the experimental change on top of `upstream/master`.

**Comment by carlreinke** [comment]
The `SDL_PauseAudio()` calls need to be replaced with [`SDL_PauseAudioDevice()`](https://wiki.libsdl.org/SDL_PauseAudioDevice).

**Comment by StephanTLavavej** [comment]
Got it, thanks! Now I hear clear audio, including when `SDL_OpenAudioDevice()` is used without `SDL_AudioStream`. And I saw what you found in the docs:

> If your application can only handle one specific data format, pass a zero for `allowed_changes` and let SDL transparently handle any differences.

Transparent handling sounds great, so I'll go ahead and update this PR accordingly.

**Comment by StephanTLavavej** [comment]
Ok, I've rebased, squashed changes, and updated the PR description. (My branch name still says `sdl-audiostream` but there's no trace of that in the code.) I removed the "requested" and "obtained" messages as you mentioned. I also noticed and fixed an issue with the hardcoded `2048` sample size. (I hope that's reasonable to include here, given how initialization is already being changed, but I can easily separate it out if desired. I suspect that given the speed of modern systems, the sample size should be halved, but I haven't done that here.)

Thanks again, this is definitely a cleaner approach.

**Review by carlreinke — APPROVED** [review]

**Pull request merged**
